### ISSUE TITLE
截图添加标注的时候，只能编辑当前的操作

### ISSUE THREAD

**Issue by ilongshan** [kzhiquan/Picsee#11]
截图添加的标注的时候，只能编辑最近一次的操作。比如我添加了两个矩形框，但是想移动一下第一个矩形框，现在就能拖动第一个矩形框，只能一步一步撤回来编辑一个矩形框。

希望能支持编辑一组操作中的任意一个。

非常好用的软件，谢谢

**Comment by kzhiquan** [comment]
@ilongshan 最近更新的1.4.0版本，已修复改问题，欢迎更新使用。
