### ISSUE TITLE
搜索的范围能否包括图片的注释

### ISSUE THREAD

**Issue by rennylf** [kzhiquan/Picsee#12]
如题

**Comment by kzhiquan** [comment]
@rennylf 可以的，不过不是在搜索框中，需要在过滤器里。如下截图操作：
![image](https://user-images.githubusercontent.com/2912180/144539411-15fc9f25-03d1-4868-beb3-b18b07cf75fa.png)

**Comment by rennylf** [comment]
谢谢你的回复，我想表达的意思其实是这样的：我给一些图片添加了描述（写在标题容易重复，标签容易越写越多），是写在注释里面。我希望搜索也能检索注释中的内容，你的回复貌似是筛选图片是否有注释，而不是检索注释的内容是否符合我的关键字。再次感谢你回复我的问题，这个软件真的很棒～

**Comment by kzhiquan** [comment]
你好，客气了。写在注释里，也可以搜索的。如上截图，勾选“有标注”，再在下面输入你的关键字，就可以把你希望有关键字的图片筛选出来了。

**Comment by rennylf** [comment]
😯 原来是注释下面还有一个搜索框，我一直没注意，感谢！
