### ISSUE TITLE
希望能提供最后一个免费版本1.4.1下载

### ISSUE THREAD

**Issue by jarryyen** [kzhiquan/Picsee#14]
希望作者可以提供下载

可以不更新新功能

可以不修复问题

但请提供最后一个免费版下载 

就像Typora

送人玫瑰,手留余香

谢谢!

祝君好!

**Comment by kzhiquan** [comment]
目前没有很好的渠道提供，建议还是更新新版本，全功能可以使用，超过限制不定时提醒，可以关掉，继续使用。
