### ISSUE TITLE
设置隐藏菜单和dock后，无法退出

### ISSUE THREAD

**Issue by 1143046586** [kzhiquan/Picsee#2]
设置隐藏菜单和dock后，找不到退出的该设置的地方，因为菜单已经被隐藏了，而且最大化显示后也无法退出

**Comment by 1143046586** [comment]
补充一下，版本为Mac Os的1.1.3版

**Comment by kzhiquan** [comment]
@1143046586 
可以在顶部状态菜单Picsee图标的下拉菜单中找到退出，如下图。
![813AEF05-2E3D-4079-8EEA-0F27D997E2EE.jpeg](https://i.imgur.com/aHMBb6A.jpg)
