### ISSUE TITLE
English typos

### ISSUE THREAD

**Issue by kuzmandi** [kzhiquan/Picsee#26]
English output is full of typos. Recommend a multi-language solution and cooperation with people of other languages.

**Comment by kzhiquan** [comment]
Yes, the English is poor, can you help me to improve the translation of Picsee. thanks @kuzmandi

**Comment by kuzmandi** [comment]
How could I do that?
Do you have a language file, which I could inspect?
Also I could offer a german translation.

**Comment by kzhiquan** [comment]
I have made an update for this repo [README](https://github.com/kzhiquan/Picsee), including how to do translation for Picsee,  I am appreciated it, if you can make a german localization and make English translation better. @kuzmandi
