### ISSUE TITLE
请问下，能否自定义显示的exif内容？

### ISSUE THREAD

**Issue by jason-shcn** [kzhiquan/Picsee#33]
如题，在默认的EXIF段落里面，
1. 缺少ISO的信息
2. 曝光时间能否换算下？目前都是“ 0.008”这样的。

**Comment by kzhiquan** [comment]
@jason-shcn 曝光时间换算已修正，感谢建议。

**Comment by kzhiquan** [comment]
@jason-shcn ISO信息 1.6.2已实现，欢迎更新使用。

Picsee 1.6.2 版本更新，欢迎升级使用.
https://picsee.chitaner.com

## v1.6.2 (2023.01.06)
- 修复裁剪覆盖保存
- 看图支持垂直翻转
- 新增ISO感光度筛选、分栏、排序
- 修复一些其他问题
