### ISSUE TITLE
问题：请问 linked folder 到底是一个什么概念？

### ISSUE THREAD

**Issue by qiulang** [kzhiquan/Picsee#36]
想请教一下 linked folder 到底是一个什么概念？我最常的使用场景就是在 Finder找到一个文件夹，然后用 Picsee看文件夹里的图片，但一直没搞懂什么才是合适操作步骤。

谢谢！

**Comment by kzhiquan** [comment]
@qiulang linked folder是管理图片时候用的概念，即可以把Finder中的文件夹，链接到Picsee内，对文件夹内的图片进行管理。Finder找到一个文件夹，查看图片，只是单单的看图。没有涉及的管理图片。其实没有什么合适的操作步骤，合适自己的就好。

**Comment by qiulang** [comment]
@kzhiquan 谢谢答复。坦白的说 查看文件夹里图片这个操作是我觉得Picsee 不然 XnViewMP方便的地方，但是 XnViewMP的界面实在太丑，比Picsee差远了。

**Comment by kzhiquan** [comment]
@qiulang 可以具体说下，哪边不方便么，我们可以讨论下，如果觉得方案可行，我们可以改进。

**Comment by qiulang** [comment]
谢谢回复，你看 XnViewMP 这个 按钮可以切换到浏览目录模式，就方便再浏览别的目录。这个功能Picsee是没有的。你试试就知道

<img width="1204" alt="XnViewMP" src="https://user-images.githubusercontent.com/516243/233784285-67c81387-c546-49ec-95a2-c364b9adf8c1.png">

**Comment by kzhiquan** [comment]
@qiulang 是的，Picsee没有这么方便，需要双击退出看图界面，才能选择文件夹查看。
