### ISSUE TITLE
Bug: 关联 SMB 共享的文件夹时，不连接共享文件夹就打开 Picsee 会一直打不开

### ISSUE THREAD

**Issue by kahosan** [kzhiquan/Picsee#38]
macOS: 13.3.1(a)
MacBook Air M1 版本

复现步骤：
1. 先在访达连接一个使用 SMB 共享的文件夹，在 Picsee 中关联这个文件夹，然后退出软件。
2. 推出 SMB 共享服务器，打开 Picsee。

**Comment by kzhiquan** [comment]
@kahosan Picsee会一直打不开什么意思？是打不开Picsee么，还是说这个文件夹打不开？

**Comment by kahosan** [comment]
Picsee 打不开

**Comment by kzhiquan** [comment]
@kahosan OK, 明白了。

**Comment by kzhiquan** [comment]
@kahosan 1.6.6版本已修复该问题，请更新使用，多谢反馈。

**Comment by kahosan** [comment]
@kzhiquan 目前已正常使用，谢谢
