### ISSUE TITLE
特定jpg文件，无法读出拍摄光圈值

### ISSUE THREAD

**Issue by jason-shcn** [kzhiquan/Picsee#40]
特定jpg文件，无法读出拍摄光圈值。光圈值是在exif中的，图片一旦通过PS或者LR修改后，就能正常读出。
P1是原图预览截屏，没有光圈数据；P2是处理后的预览截屏，有光圈数据。第三张是原始图片。
相机是徕卡MP240。
<img width="1175" alt="p1" src="https://github.com/kzhiquan/Picsee/assets/25949296/1a6f06af-46ff-43b3-8b11-5f45f05eb8cf">
<img width="1377" alt="p2" src="https://github.com/kzhiquan/Picsee/assets/25949296/2404ac2f-e24a-4f1a-8930-3aa383a7e6d6">
![L1000906](https://github.com/kzhiquan/Picsee/assets/25949296/d6a73481-97ee-4eb4-b370-d69b606c41c5)

**Comment by kzhiquan** [comment]
![image](https://github.com/kzhiquan/Picsee/assets/2912180/c723e0fb-660a-48e4-abec-c6e53add5f49)
![image](https://github.com/kzhiquan/Picsee/assets/2912180/ed384213-fd86-4818-ba0b-fe4dabd7864d)
光圈数和光圈值是不同的，新的版本会增减光圈值这个字段。

**Comment by kzhiquan** [comment]
@jason-shcn 1.6.6版本已修复改问题，请更新使用，多谢反馈。
