### ISSUE TITLE
icloud 同步是谁的账号，默认同步的吗，会盗用用户隐私吗

### ISSUE THREAD

**Issue by ZenoHu** [kzhiquan/Picsee#41]

**Comment by ZenoHu** [comment]
![image](https://github.com/kzhiquan/Picsee/assets/30396902/31462b9f-09ff-4fc1-902e-c40faad87898)
请问这个上传到 SM.MS/Anony 是谁的账号？

**Comment by kzhiquan** [comment]
@ZenoHu 用系统的自带的iCloud账号，开发者看不到。导出到SM.MS/Anony是公开的，导出到这个网盘，任何人可查看，但是匿名的。可以使用自己的图床，在设置中配置。
