### ISSUE TITLE
无法添加又拍云

### ISSUE THREAD

**Issue by Dion-Lee** [kzhiquan/Picsee#42]
添加又拍云报错
<img width="610" alt="iShot_2023-09-16_08 07 52" src="https://github.com/kzhiquan/Picsee/assets/68332968/e21c4ccc-739d-4a6c-9144-c2c8d53142e9">

**Comment by kzhiquan** [comment]
@Dion-Lee 能否私发我填的详细信息？多谢。

**Comment by Dion-Lee** [comment]
> @Dion-Lee 能否私发我填的详细信息？多谢。

发你邮箱了
