### ISSUE TITLE
点击检查更新跳转到 App Store

### ISSUE THREAD

**Issue by cooper1x** [kzhiquan/Picsee#43]
第一次下载打开，有个弹窗提示升级，但是更新很慢我就取消了。

第二次打开的时候，点击更新，发现跳转到 App Store，而且 App Store 的版本还是一个月前。

我是官网下载的 dmg ，希望可以直接在软件内更新。
<img width="531" alt="image" src="https://github.com/kzhiquan/Picsee/assets/9080789/3bcc9c0e-36bf-46c6-9b9e-402b89914132">

**Comment by kzhiquan** [comment]
@cooper1x 你好，现在已修复，先前是把下载放在github release中，所以下载慢，现在换其他地方了，国内应该能保障速度。请重新在官网上下载使用，感谢支持。
