### ISSUE TITLE
能否方便的设置picsee为默认图片查看应用，图片文件格式太多，一个一个设置好麻烦

### ISSUE THREAD

**Issue by chc880** [kzhiquan/Picsee#5]

**Comment by kzhiquan** [comment]
嗯，目前是一个一个格式的设置，通过右键菜单，显示简介，我研究下，MacOS下是否有统一的设置方式。

**Comment by kzhiquan** [comment]
@chc880 可以参考下这篇：https://picsee.chitaner.com/blog/Mac%E4%B8%8A%E8%AE%BE%E7%BD%AE%E9%BB%98%E8%AE%A4%E6%89%93%E5%BC%80%E7%A8%8B%E5%BA%8F.html。
