### ISSUE TITLE
无法显示索尼相机 raw 文件

### ISSUE THREAD

**Issue by linking2014** [kzhiquan/Picsee#6]
索尼 A7C 未压缩 raw 文件跟 jpg 在同一个文件夹，用 Picsee 看图显示空白。
可否支持此 raw 文件，或者筛选文件夹内的图片格式看图？
![软件截图](http://cdn.zhaorulin.com/upic/2021-03-17-xHLzVp.png)

**Comment by kzhiquan** [comment]
你好，可以的，能否发我下，索尼 A7C 未压缩 raw 文件, 好调试下，cr2, cr3现在是支持的。

**Comment by 18271211** [comment]
cr2 也不显示，反复试了很多次。

**Comment by kzhiquan** [comment]
@18271211 能否方便提供下不显示的cr2图片，本地复现不了，多谢。

**Comment by kzhiquan** [comment]
@linking2014 感谢对软件的使用

**Comment by linking2014** [comment]
> 你好，可以的，能否发我下，索尼 A7C 未压缩 raw 文件, 好调试下，cr2, cr3现在是支持的。

抱歉最近有点忙忘了这回事，这里是链接

链接: https://pan.baidu.com/s/1_v9pLZIXCeeXy2I4e5-tVA 
提取码: st9q

**Comment by kzhiquan** [comment]
@linking2014 Picsee1.3.4版本已支持arw格式的显示，欢迎下载更新，谢谢对软件的支持。

**Comment by linking2014** [comment]
> @linking2014 Picsee1.3.4版本已支持arw格式的显示，欢迎下载更新，谢谢对软件的支持。

谢谢，辛苦了
