### ISSUE TITLE
排序功能有问题

### ISSUE THREAD

**Issue by Timess** [kzhiquan/Picsee#7]
正常来说应该是：01 02 03 ... 10 11 12.jpg
实际却是：01 02 03 ... 10 100 101 102 .. 109 11 110 111.jpg

**Comment by kzhiquan** [comment]
最新的1.2.9版本已经修复该问题，请更新，更新后，请重建当前资源束索引，即可修复。

**Comment by kzhiquan** [comment]
@Timess 感谢对软件的使用。
